### ISSUE TITLE
Travis Build Is Failing.

### ISSUE THREAD

**Issue by divyanshu-rawat** [systers/celebration#16]
## Description
As a Systers Community Member,
I need make sure Travis is working properly,
so that I can ensure that changes committed by me are not breaking any existing functionality.

## Mocks
![screen shot 2018-04-25 at 1 14 29 pm](https://user-images.githubusercontent.com/13464678/39232357-aaa10272-488a-11e8-84ea-ddcf9a6149bc.png)

![screen shot 2018-04-25 at 1 16 23 pm](https://user-images.githubusercontent.com/13464678/39232424-e40517e2-488a-11e8-94aa-c7520b806c0e.png)

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
Can't Estimated

**Comment by BaaniLeen** [comment]
@divyanshu-rawat Since tests have not been written for this repo yet, what is the purpose of having a Travis CI?

**Comment by divyanshu-rawat** [comment]
@BaaniLeen I do agree with you on the same but as far as I know, right now Travis is failing because of some other reasons maybe configuration issues in .travis.yml I guess.

**Comment by BaaniLeen** [comment]
@divyanshu-rawat Can I remove the .travis.yml file as suggested by May? Can you assign me the issue to work upon?

**Comment by divyanshu-rawat** [comment]
@BaaniLeen actually @MeepyMay has already turned off Travis CI.
I don't think .travis.yml is causing any harm so I think we can keep it until we write test cases.
And currently it will not build anything as it's being turned off by @MeepyMay .

**Comment by BaaniLeen** [comment]
@divyanshu-rawat Great! That works then! :)
Shall we close this issue since it has been resolved?

**Comment by divyanshu-rawat** [comment]
@BaaniLeen sure 👍
