### ISSUE TITLE
Adding Travis CI 

### ISSUE THREAD

**Issue by Tharangi** [systers/celebration#9]
## Description
As a Systers GitHub page developer,
I need to set to automatically build pull requests and adds the output to those PRs,
so that I can see if it is safe to merge a request without building it locally.

## Mocks
N/A

### Travis CI integration
- [ ] Automatically build pull requests.
- [ ] Automatically add outputs to built PRs. 

## Definition of Done
- [ ] All of the required items are completed.

## Estimation
0.25 hours

**Comment by prachi1210** [comment]
I don't think we have tests written for this repository so Travis CI is not really of any use here.
